# Generated by Django 4.2.1 on 2023-05-23 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Product')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('brand', models.CharField(max_length=255, null=True, verbose_name='Brand')),
                ('size', models.CharField(max_length=255, null=True, verbose_name='Size')),
                ('content', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Price $')),
                ('images', models.ImageField(blank=True, null=True, upload_to='products')),
                ('img_thumb', models.ImageField(blank=True, null=True, upload_to='products/thumb')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('published', models.BooleanField(default=True, verbose_name='Published')),
                ('author', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
